### ISSUE TITLE
to-title-case is hot garbage, replace it

### ISSUE THREAD

**Issue by sbma44** [ingalls/pt2itp#137]
it is much too clever for its own good:

```
> const t = require('to-title-case')
> t('Väike-Sõjamäe')
'V Ike S Jam E'
> t('Väike Sõjamäe')
'Väike Sõjamäe'
> t('VäikeSõjamäe')
'Väike Sõjamäe'
```

Let's just implement a replacement in the project. @ingalls requests that it also handle double spaces. We should use the same word boundaries as carmen:

```
const WORD_BOUNDARY = "[\\s\\u2000-\\u206F\\u2E00-\\u2E7F\\\\'!\"#$%&()*+,\\-.\\/:;<=>?@\\[\\]^_`{|}~]";
```

**Comment by sbma44** [comment]
titlecasing requires a list of non-principal words. I forked https://github.com/mapbox/title-case-minors-fork but we should make this a private dupe so we can open issues on it. Waiting on someone from #security to delete the repo so I can do that. Once they do I'll ticket multilingual.

**Comment by sbma44** [comment]
working branch is https://github.com/ingalls/pt2itp/tree/titlecase incidentally

**Comment by apendleton** [comment]
Just wanted to note some reservations about applying a title case operation, as it's kind of English-specific and we'll want to think through how it applies to non-English text. Specifically:
* not all languages have case at all (this I think we can ignore)
* of those that do, not all have a notion of "title" case, which is to say, most words init-capitalized except a few special cases that aren't. [Some languages](https://www.thoughtco.com/capitalize-french-titles-4086495) have really complicated rules in titles about what gets capitalized and what doesn't, some just init-cap everything, and some may only ever do sentence case
* of those that do, it goes without saying that the special words will vary, and that a special word in one language may also by happenstance be a word in a different language that doesn't get special treatment
* the specifics of how title case is applied will also not be uniform around, for example, tokenization. "pont d'avignon" in French would properly be title-cased "Pont d'Avignon" where "d'" is a contraction of a preposition and "Avignon" is the object of that preposition, so capitalization ends up getting applied mid-contraction in French, whereas you would never expect "St. Peter'S church" in English; English contractions are treated as a single unit for purposes of capitalization (with the possible exception of some borrowed names like "O'Brien"). "Pont D'Avignon" in French would be slightly funny-looking, but basically the equivalent of "init caps" instead of "title case" in English. "Pont D'avignon" would be incorrect.

If I can think of any more weird corner cases I'll add them.

**Comment by sbma44** [comment]
Good objections! My plan had been to move the title-case protected words to a per-language mapping file, but I think it's going to make more sense to make this adjustment pluggable on a per-country basis, including the decision about whether to use the `network` or `address` data source's text field as the basis for the label.

**Comment by apendleton** [comment]
Sounds good. Not an exact fit, but maybe of interest: http://libguides.dickinson.edu/citing/mla7capitalization . Looks like the biggest gotcha is maybe that most Romance languages don't seem to capitalize the "street" or "mountain" words in place names.

**Comment by sbma44** [comment]
OK: I've got a branch where the behavior that selects and transforms the output text label is pluggable. I've made the default behavior:

- use english titlecase behavior, same as current behavior
- except not broken
- when diacriticless & caseless address & network text are identical, use the version that seems to have more case information

Based on http://mylanguages.org/estonian_articles.php and http://download.microsoft.com/download/1/a/9/1a9ebe06-0c0a-4182-b516-403d842b7555/est-est-StyleGuide.pdf I think that for Estonian we can continue to use the English titlecasing without doing anything _too_ horrible, which means no adjustments to `mapbox-places-address` for now, but I won't be surprised if we have to adjust later.

**Comment by sbma44** [comment]
Test mode makes this look like it's working. A sample of remaining failures (only 6000 total when run with `--name=token`)

```
TEXT FAIL => '6 paemurru tn' !== '11 6 paemurru tn'|11 6. Paemurru tänav|28.164842,59.369872
TEXT FAIL => '19 a h tammsaare tee' !== '19 a h tammsaare tn'|19 A. H. Tammsaare tänav|27.396391,59.359921
TEXT FAIL => '2 joesuu tn' !== '17 2 joesuu tn'|17 2. Jõesuu tänav|28.189715,59.394512
NO RESULTS|27 1. Mai puiestee|25.953492,59.259522
DIST FAIL - 3.00km - returned: 23.546071,58.947727|22b Lihula maantee|23.546459,58.920775
NO RESULTS|3 26. Juuli tänav|28.184315,59.365511
NAME MISMATCH: Network: aleksander puskini vs: |65 aleksander pudhkini|28.181641,59.392375
NAME MISMATCH: Network: maneezi vs: |7 maneethi|24.760919,59.436303
NAME MISMATCH: Network: sudiste vs: |10 suvila|25.606363,58.077288
NAME MISMATCH: Network: joorde vs: |3 joodre|23.62793,58.867024
NAME MISMATCH: Network: kiisapalu 4 vs: |23 kiisapalu|24.676749,59.243784
NAME MISMATCH: Network: c r jakobsoni vs: |23 carl robert jakobsoni|26.353798,59.351575
NAME MISMATCH: Network: untaaugu vs: |1 untaugu|25.155555,59.528682
NAME MISMATCH: Network: aiatee vs: |38 aia|24.843392,59.492791
NAME MISMATCH: Network: vana tartu vs: |8 vana vaida|24.97369,59.286522
NAME MISMATCH: Network: elutee vs: |3 elu|24.403719,58.3972
NAME MISMATCH: Network: kivioli varja vs: |17 kivioli|26.998207,59.366362
NAME MISMATCH: Network: mihhail gorbatsi vs: |10 mihhail gorbatdhi|28.158452,59.40441
NAME MISMATCH: Network: limnoloogiajaama vs: |1 limnoloogia|26.109033,58.210804
NAME MISMATCH: Network: mao abt vs: |9 mao|25.580315,58.906317
NAME MISMATCH: Network: majaka vs: |15 meleka|24.243915,59.381267
```

I can dig into these more, but my sense is we're getting down to address number parsing problems and minor imperfections in the data. Keep in mind that that 6k number reflects every mismatched point, not just every mismatched way.

**Comment by sbma44** [comment]
merged some improvements https://github.com/ingalls/pt2itp/pull/139
